const sidebar = {
  '/base/linux/': [
    '1.index',
    '2.webpack',
    '3.file',
    '4.single',
    '5.page',
    '7.module',
    '8.project',
    '9.utils',
    '10.ui',
    '11.data',
    '12.skill',
    '13.com',
    '14.data',
    '15.api',
  ],
  '/base/auth/': [
    '1.index',
    '2.Jenkins',
    '3.gitlab',
    'vscode',
    'test',
    'prem',
    'i18n'
  ],

  '/base/system/': [
    '1.index',
    '2.Jenkins',
    '3.gitlab',
    'vscode',
    'test',
    'prem',
    'i18n'
  ],
  '/base/service/': [
    '1.index',
    '2.Jenkins',
    '3.gitlab',
    'vscode',
    'test',
    'prem',
    'i18n'
  ],
  '/base/network/': [
    '1.index',
    '2.Jenkins',
    '3.gitlab',
    'vscode',
    'test',
    'prem',
    'i18n'
  ],
  '/application/vi/': [
    '1.index',
    '1.docker',
    '2.Jenkins',
    '3.gitlab',
    'vscode',
    'test',
    'prem',
    'i18n'
  ],
  '/application/user/': [
    '1.index',
    '2.Jenkins',
    '3.gitlab',
    'vscode',
    'test',
    'prem',
    'i18n'
  ],
  '/application/shell/': [
    '1.index',
    '2.Jenkins',
    '3.gitlab',
    'vscode',
    'test',
    'prem',
    'i18n'
  ],
  '/application/install/': [
    '1.index',
    '2.Jenkins',
    '3.gitlab',
    'vscode',
    'test',
    'prem',
    'i18n'
  ],
  '/senior/nginx/': [
    '1.index',
    '2.extend',
    '3.componentCommunication',
    '4.render',
    '5.api',
    '6.form',
    '7.checkBox',
    '8.active',
    '9.alert',
    '10.table',
    '11.tree'
  ],
  '/senior/docker/': [
    '1.index',
    '2.extend',
    '3.componentCommunication',
    '4.render',
    '5.api',
    '6.form',
    '7.checkBox',
    '8.active',
    '9.alert',
    '10.table',
    '11.tree'
  ],
  '/senior/jenkins/': [
    '1.index',
    '2.extend',
    '3.componentCommunication',
    '4.render',
    '5.api',
    '6.form',
    '7.checkBox',
    '8.active',
    '9.alert',
    '10.table',
    '11.tree'
  ],
  '/senior/groovy/': [
    '1.index',
    '2.extend',
    '3.componentCommunication',
    '4.render',
    '5.api',
    '6.form',
    '7.checkBox',
    '8.active',
    '9.alert',
    '10.table',
    '11.tree'
  ],
  '/senior/php/': [
    '1.index',
    '2.extend',
    '3.componentCommunication',
    '4.render',
    '5.api',
    '6.form',
    '7.checkBox',
    '8.active',
    '9.alert',
    '10.table',
    '11.tree'
  ],
  '/senior/java/': [
    '1.index',
    '2.extend',
    '3.componentCommunication',
    '4.render',
    '5.api',
    '6.form',
    '7.checkBox',
    '8.active',
    '9.alert',
    '10.table',
    '11.tree'
  ],
  '/senior/node/': [
    '1.index',
    '2.extend',
    '3.componentCommunication',
    '4.render',
    '5.api',
    '6.form',
    '7.checkBox',
    '8.active',
    '9.alert',
    '10.table',
    '11.tree'
  ],
  '/senior/k8s/': [
    '1.index',
    '2.extend',
    '3.componentCommunication',
    '4.render',
    '5.api',
    '6.form',
    '7.checkBox',
    '8.active',
    '9.alert',
    '10.table',
    '11.tree'
  ],
  '/source/vue/': [
    '1.preparation',
    '2.dataDriven',
    '3.componentization',
    '4.deepResponsePrinciple',
    '5.compile',
    '6.extend',
    '7.vueRouter',
    '8.vuex'
  ],
}
module.exports = sidebar;
